### ISSUE TITLE
Tuck the dotnet installation inside the action

### ISSUE THREAD

**Issue by DannyBen** [retypeapp/action-build#14]
Is it possible to hide the dotnet installation step from the user?

Perhaps here?
https://github.com/retypeapp/action-build/blob/b000ba7cf31565de2ea0afa90446d91fddf4520a/action.yml#L27-L30

I would love to just do

```yaml
steps:
- uses: actions/checkout@v2
- uses: retypeapp/action-build
```

instead of 

```yaml
steps:
- uses: actions/checkout@v2

- uses: actions/setup-dotnet@v1
  with:
    dotnet-version: 5.0.x

- uses: retypeapp/action-build
```
