### ISSUE TITLE
Support to specify path to retype.json via input argument

### ISSUE THREAD

**Issue by fabriciomurta** [retypeapp/action-build#2]
It should be possible to point to a **retype.json** file anywhere within the repository and current branch.

**Comment by fabriciomurta** [comment]
We decided to add a single input to pass the path/config to the file, like:

```yaml
- using: retypeapp/action-build@v1
  with:
    config: docs/retype.json
```

It should also support pointing to the directory, where retype would look for an existing **retype.json** file or assume defaults if none specified.

```yaml
- using: retypeapp/action-build@v1
  with:
    config: docs
```
