### ISSUE TITLE
retype.yml not found in root directory, despite being there

### ISSUE THREAD

**Issue by pdimens** [retypeapp/action-build#23]
Hello, I'm trying to build/publish a retype site and it will not recognize the `retype.yml` in the root directory of my branch, nor can I seem to specify it correctly with
```yaml
      - uses: retypeapp/action-build@latest
        with:
          config: retype.yml
```
however  I **do** have a `retype.yml` in my root directory. It was created by `retype watch` and modified by me. Here is the folder structure of my branch:
![image](https://user-images.githubusercontent.com/19176506/219169577-4b7b0d12-7100-4f5d-b3ac-52cbba304d6e.png)

screenshot:
![image](https://user-images.githubusercontent.com/19176506/219168622-9e8d0159-51a2-4e90-ab98-48ff07cd9305.png)

Might you understand why this is happening?
