### ISSUE TITLE
Action fails with dotnet version 7.x.x

### ISSUE THREAD

**Issue by ChandranshuRao14** [retypeapp/action-build#24]
When using `actions/setup-dotnet` with version `7.x.x`, the job consistently fails with the error message:
```
Can't find suitable dotnet or node installation to install retype package with.
```

Workflow file:
```
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0.x

      - name: Build doc site
        uses: retypeapp/action-build@latest
        with:
          license: ${{ secrets.RETYPE_LICENSE_KEY }}
```

I believe this line https://github.com/retypeapp/action-build/blob/main/build.sh#L28 is only checking for dotnet --version == 5 which is causing this issue. I tried to use setup-dotnet with dotnet-version: 5.x.x as a workaround, but this didn't work for retype version 3.0.3 as it required atleast dotnet v 7.

**Comment by geoffreymcgill** [comment]
Thanks for pointing out this issue. We will test and try to fix the action-build right away.

**Comment by geoffreymcgill** [comment]
@ChandranshuRao14 I was not able to reproduce the error you received. 

Can you review our **retype-action.yml** file for the retype.com website and let me know what changes would be required to reproduce?

https://github.com/retypeapp/retype/blob/main/.github/workflows/retype-action.yml

The workflow run is available at:

https://github.com/retypeapp/retype/actions/runs/5459029755/jobs/9934633439

What system are you running your jobs on? Currently, the above is configured to run on `runs-on: ubuntu-latest`. 

https://github.com/retypeapp/retype/blob/f5a5ff57b20ef2efb197416d8043b586ac4693de/.github/workflows/retype-action.yml#L12

**Comment by geoffreymcgill** [comment]
I committed a potential fix for the action-build and you can test in your projects **retype-action.yml** file.

Just change the following line:

```yml
# Existing
# - uses: retypeapp/action-build@latest

# Revised
- uses: retypeapp/action-build@issue-1648
```

The revised `issue-1648` branch of action-build includes the following fix:

https://github.com/retypeapp/action-build/pull/25/files#diff-4d2a8eefdf2a9783512a35da4dc7676a66404b6f3826a8af9aad038722da6823R28

Hope this helps.

**Comment by ChandranshuRao14** [comment]
@geoffreymcgill thanks for your swift response!

> The workflow run is available at:
> 
> https://github.com/retypeapp/retype/actions/runs/5459029755/jobs/9934633439

It looks like although the job succeeded, the `retypeapp/action-build` step fell back on using `npm` to install the retype cli as noted [here](https://github.com/retypeapp/retype/actions/runs/5459029755/jobs/9934633439#step:4:18):

```
Installing Retype v3.0.3 using NPM package manager (linux-x64): done.
```

GitHub Actions runners have `node` and `npm` [installed by default](https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md#package-management), but not dotnet which explains why falling back to npm still succeeded.
 
> What system are you running your jobs on? Currently, the above is configured to run on `runs-on: ubuntu-latest`.

We self-host runners on Kubernetes using [actions/actions-runner-controller](https://github.com/actions/actions-runner-controller). We use a custom docker image for our runners that use [this docker image](https://github.com/actions/actions-runner-controller/blob/master/runner/actions-runner.ubuntu-22.04.dockerfile) as a base and we install some of our tooling on top of it. Our docker image is missing `node` and `npm` though

**Comment by ChandranshuRao14** [comment]
I tried the fix you've provided `retypeapp/action-build@issue-1648` and that resolved our initial issue! However, we're now seeing a different error:

```
Run retypeapp/action-build@issue-1648
Run ${GITHUB_ACTION_PATH}/build.sh
Working directory is: /runner/_work/container-infra/container-infra
Installing Retype v3.0.3 using dotnet tool: done.
Determining temporary target folder to place parsed documentation: /tmp/tmp.7LDcJCN6Lf
Setting up build arguments: /retype.yml, license key, done.
Building documentation: error.
Error: retype build command failed with exit code 1.
Failed command and output:

$ retype build --verbose --secret *** --override {
  "output": "/tmp/tmp.7LDcJCN6Lf"
}

/runner/_work/_actions/retypeapp/action-build/issue-1648/build.sh: line 158: retype: command not found
----

Aborting documentation build process.
Error: Process completed with exit code 1.
```

I think this could be resolved by updating the path in the build script?
```
export PATH="$PATH:/home/runner/.dotnet/tools"
```

**Comment by fabriciomurta** [comment]
The path you mention should probably be set up by the `setup-dotnet` step, as it is the path to dotnet tools installed via `dotnet tool install <name>`. Do you get any warnings or notices in the `setup-dotnet` step?

Does it work if you install another tool? Perhaps the simple `dotnetsay` one:

```YAML
  steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0.x

      - name: Install a tool
        run: dotnet install --global dotnetsay

      - name: Run the installed tool
        run: dotnetsay hello
```

If this also does not work then probably something on your custom runner does not allow a proper installation of the `dotnet` CLI. If you don't have or want to have .NET set up in the host, then NodeJS (through NPM).

Could, by any reason, your tooling be conflicting with the .NET setup?

I'm not sure we should fix ourselves this missing path in retype action, as, once the `dotnet` CLI is chosen, it will rely on its settings, and retype won't choose a path on its own when installed via `dotnet tool install --global retypeapp`.

Hope this helps!
