### ISSUE TITLE
Support building and deploying multiple Retype projects

### ISSUE THREAD

**Issue by geoffreymcgill** [retypeapp/action-build#30]
Currently, it is only possible to build one Retype project using the `action-build` workflow action, using the following configuration:

```yml
 - uses: retypeapp/action-build@latest
 ```

Ideally it would be possible to build multiple instances and configure a custom output location for each of those builds. This would enable scenarios where targeting individual builds to separate languages would be possible. For instance, the following configuration where a `FR`, `KO`, and default Englsih build would be possible if multiple builds configurations were supported:

```yml
      - uses: retypeapp/action-build@latest
        with:
            config_path: fr/retype.yml
            output: fr

      - uses: retypeapp/action-build@latest
        with:
            config_path: ko/retype.yml
            output: ko

      - uses: retypeapp/action-build@latest
```

The following project demonstrates the entire scenario:

https://github.com/retypeapp/two-lang-demo
